version: "3.8"
services:
    mongodb:
        image: mongo
        restart: always
        ports: 
            - "27017:27017"
        volumes: 
            - "../db:/data/db/"

    nodejs:
        build: .
        restart: always
        ports: 
            - "3000:3000"
        volumes:
            - "../app2:/opt/app"
        working_dir: /opt/app/
        command: >
            sh -c "ls -l &&
            ./wait-for-it.sh mongodb:27017 &&
            npm run dev
            "
        depends_on:
            - "mongodb"